'''
DOW JONES INDUSTRIAL 'DJI' - INDEX
USD/MXN - DIVISA
__________________________________
REQUERIMENTOS:

+ DATOS HISÓRICOS 4HRS / DIARIO DE USD MXN (ISRAEL)
+ DATOS HISTÓRICOS 4HRS / DIARIOS DE DOW JONES (ISRAEL)
+ 2009-2019 TEST ---> 2019-2020 TEST
_________________________________
PUNTOS:

+ VARIABLES ENDÓGENAS
1) REGRESIÓN SIMBÓLICA ---> PRONOSTICAR PRECIOS? LINEAL
2) UTILIZAR LA INFO DE UNA PARA LLEGAR A OTRO
3) REVISAR VALORES ATÍPICOS (0/1 DENTRO DE UNA MATRIZ DE VARIABLES O X DESVIACIÓN DE LA MEDIA MÓVIL) - NORMALIZAR
    + RENDIMIENTOS
    + VOLATILIDADES
    + DESVIACIONES ESTÁNDAR
    + TRANSFORMACIONES NO-LINEALES (CHECAR LAS DEL PAP?)
    + PRUEBAS ESTADÍSTICAS
4) PRUEBAS ESTADÍSTICAS PARA ACEPTACIÓN DE VARIABLES
5) CUANTO VAMOS A INVERTIR?
__________________________________
ETAPA 1:

1) DATA QUEDARA LA ESTRUCTURA DE OANDA (CHECAR DEL PAP, PERO CON CREDENCIALES DE ISRAEL)
2) MAIN DE DATOS HISTÓRICOS DE AMBOS

__________________________________
ETAPA 2:



'''
